# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ef7f1238898896542af5834407935a108772b615da902987143e77feb59bf9596583ac2c781029b4fd3604d28524c7237a28443ea55ee056a677c94ec707de7a

test:
  secret_key_base: 17f1d99574569cfbc78e0e8008d2b6b0e960aec983c06ef245c542b3112048a604396f0da41c63cf913f41d89da23954ec08d980c545384ac5bdadcb9882b187

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
